'use client'

import { useMemo } from 'react'
import { format, formatDistanceToNow } from 'date-fns'

// ─── Types ────────────────────────────────────────────────────────────────────

type ActivityStatus = 'completed' | 'failed' | 'pending'

interface AgentActivity {
  id: string
  label: string
  description: string
  timestamp: Date | null
  status: ActivityStatus
  model: string
  source: string
  detail?: string
}

interface AgentActivityPanelProps {
  opportunity: any
  assessment: any
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function deriveActivities(opportunity: any, assessment: any): AgentActivity[] {
  const activities: AgentActivity[] = []

  // 1. Opportunity added to USHER (always present)
  if (opportunity?.createdAt) {
    activities.push({
      id: 'opp-added',
      label: 'Opportunity indexed',
      description: 'Solicitation data fetched from SAM.gov and stored',
      timestamp: new Date(opportunity.createdAt),
      status: 'completed',
      model: 'SAM.gov API',
      source: 'SAM.gov Opportunities API',
      detail: opportunity.solicitationNumber
        ? `Solicitation ${opportunity.solicitationNumber}`
        : undefined,
    })
  }

  // 2. Attachments parsed
  const parsedAttachments = opportunity?.parsedAttachments as any
  if (parsedAttachments?.parsedAt) {
    const parsedCount = parsedAttachments.parsedCount ?? parsedAttachments.parsed?.length ?? 0
    const totalCount = parsedAttachments.totalAttachments ?? 0
    const hasFailed = parsedCount < totalCount
    activities.push({
      id: 'attachments-parsed',
      label: 'Solicitation documents parsed',
      description: hasFailed
        ? `Parsed ${parsedCount} of ${totalCount} attachments — some could not be read`
        : `Extracted text and structured content from ${parsedCount} solicitation attachment${parsedCount !== 1 ? 's' : ''}`,
      timestamp: new Date(parsedAttachments.parsedAt),
      status: hasFailed ? 'failed' : 'completed',
      model: 'pdf-parse / mammoth',
      source: 'Attachment Parser',
      detail: totalCount > 0
        ? `${parsedCount}/${totalCount} documents · ${parsedAttachments.structured?.scope?.length ?? 0} scope items extracted`
        : undefined,
    })
  }

  // 3. Opportunity brief generated
  const brief = opportunity?.opportunityBrief as any
  if (brief?.generatedAt) {
    activities.push({
      id: 'brief-generated',
      label: 'Opportunity brief generated',
      description: 'Plain-language summary of what the agency is buying, who qualifies, and key gotchas',
      timestamp: new Date(brief.generatedAt),
      status: 'completed',
      model: 'GPT-4o',
      source: 'OpenAI',
      detail: brief.estimatedValue && brief.estimatedValue !== 'Not stated'
        ? `Estimated value: ${brief.estimatedValue}`
        : brief.contractType
          ? `Contract type: ${brief.contractType}`
          : undefined,
    })
  }

  // 4. Assessment created / updated
  if (assessment?.createdAt) {
    const isAutoGenerated =
      assessment.notes?.includes('USASpending') ||
      assessment.notes?.includes('usaspending') ||
      !assessment.notes
    activities.push({
      id: 'assessment-created',
      label: 'Bid assessment created',
      description: `Go/no-go analysis: ${assessment.recommendation ?? 'Pending'} · margin ${
        assessment.profitMarginPercent != null
          ? `${assessment.profitMarginPercent.toFixed(0)}%`
          : '—'
      }`,
      timestamp: new Date(assessment.createdAt),
      status: 'completed',
      model: isAutoGenerated ? 'Rule-based engine' : 'Manual',
      source: 'Margin Calculator',
      detail:
        assessment.estimatedValue != null
          ? `Value: $${formatCurrency(assessment.estimatedValue)} · Cost: $${formatCurrency(assessment.estimatedCost ?? 0)}`
          : undefined,
    })
  }

  // 5. Assessment updated (if updatedAt differs materially from createdAt)
  if (
    assessment?.updatedAt &&
    assessment?.createdAt &&
    Math.abs(
      new Date(assessment.updatedAt).getTime() - new Date(assessment.createdAt).getTime()
    ) > 60_000
  ) {
    activities.push({
      id: 'assessment-updated',
      label: 'Bid assessment updated',
      description: `Revised estimates — recommendation: ${assessment.recommendation ?? '—'}`,
      timestamp: new Date(assessment.updatedAt),
      status: 'completed',
      model: 'Manual',
      source: 'Margin Calculator',
    })
  }

  // 6. SOW(s) generated
  const sows: any[] = opportunity?.sows ?? []
  for (const sow of sows) {
    const sowContent = sow.content as any
    const usedOpenAI = sowContent?.sourceEnhanced !== false
    activities.push({
      id: `sow-generated-${sow.id}`,
      label: sow.version > 1 ? `SOW v${sow.version} generated` : 'Statement of Work generated',
      description: `${usedOpenAI ? 'GPT-4o drafted sections 1–6 from parsed solicitation content' : 'Rule-based sections built from solicitation metadata'}`,
      timestamp: new Date(sow.createdAt),
      status: 'completed',
      model: usedOpenAI ? 'GPT-4o' : 'Rule-based builder',
      source: usedOpenAI ? 'OpenAI' : 'USHER',
      detail: sow.fileName ?? undefined,
    })
  }

  // 7. Subcontractors discovered
  const subs: any[] = opportunity?.subcontractors ?? []
  if (subs.length > 0) {
    // Group by discovery batch (same-minute createdAt = same discovery run)
    const batches = new Map<string, any[]>()
    for (const sub of subs) {
      const bucketKey = sub.createdAt
        ? new Date(sub.createdAt).toISOString().slice(0, 16) // YYYY-MM-DDTHH:MM
        : 'unknown'
      if (!batches.has(bucketKey)) batches.set(bucketKey, [])
      batches.get(bucketKey)!.push(sub)
    }

    for (const [bucketKey, batch] of batches.entries()) {
      const googleCount = batch.filter((s) => s.source === 'google_places').length
      const samCount = batch.filter((s) => s.source === 'sam_gov').length
      const manualCount = batch.filter(
        (s) => s.source !== 'google_places' && s.source !== 'sam_gov'
      ).length

      const sourceLabel =
        googleCount > 0 && samCount > 0
          ? 'Google Places + SAM.gov'
          : googleCount > 0
          ? 'Google Places'
          : samCount > 0
          ? 'SAM.gov'
          : 'Manual'

      const parts: string[] = []
      if (googleCount > 0) parts.push(`${googleCount} via Google Maps`)
      if (samCount > 0) parts.push(`${samCount} via SAM.gov`)
      if (manualCount > 0) parts.push(`${manualCount} added manually`)

      const earliest = batch.reduce((min, s) => {
        const d = new Date(s.createdAt)
        return d < min ? d : min
      }, new Date(batch[0].createdAt))

      activities.push({
        id: `subs-discovered-${bucketKey}`,
        label: `${batch.length} subcontractor${batch.length !== 1 ? 's' : ''} discovered`,
        description: parts.join(', ') || `${batch.length} vendors found`,
        timestamp: earliest,
        status: 'completed',
        model: sourceLabel,
        source: sourceLabel,
        detail:
          googleCount > 0 && opportunity.naicsCode
            ? `NAICS ${opportunity.naicsCode} · ${opportunity.state ?? ''}`
            : undefined,
      })
    }
  }

  // Sort chronologically (oldest first)
  return activities.sort((a, b) => {
    if (!a.timestamp) return 1
    if (!b.timestamp) return -1
    return a.timestamp.getTime() - b.timestamp.getTime()
  })
}

function formatCurrency(amount: number): string {
  if (amount >= 1_000_000) return `${(amount / 1_000_000).toFixed(1)}M`
  if (amount >= 1_000) return `${(amount / 1_000).toFixed(0)}K`
  return amount.toLocaleString()
}

// ─── Icons ────────────────────────────────────────────────────────────────────

function IconDatabase() {
  return (
    <svg className="h-3.5 w-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4 7c0-1.657 3.582-3 8-3s8 1.343 8 3M4 7v5c0 1.657 3.582 3 8 3s8-1.343 8-3V7M4 12v5c0 1.657 3.582 3 8 3s8-1.343 8-3v-5" />
    </svg>
  )
}

function IconDocument() {
  return (
    <svg className="h-3.5 w-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z" />
    </svg>
  )
}

function IconSparkles() {
  return (
    <svg className="h-3.5 w-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z" />
    </svg>
  )
}

function IconUsers() {
  return (
    <svg className="h-3.5 w-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0z" />
    </svg>
  )
}

function IconCalculator() {
  return (
    <svg className="h-3.5 w-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 7h6m0 10v-3m-3 3h.01M9 17h.01M9 14h.01M12 14h.01M15 11h.01M12 11h.01M9 11h.01M7 21h10a2 2 0 002-2V5a2 2 0 00-2-2H7a2 2 0 00-2 2v14a2 2 0 002 2z" />
    </svg>
  )
}

function getActivityIcon(activityId: string) {
  if (activityId.startsWith('opp-')) return <IconDatabase />
  if (activityId.startsWith('attachments-')) return <IconDocument />
  if (activityId.startsWith('brief-')) return <IconSparkles />
  if (activityId.startsWith('assessment-')) return <IconCalculator />
  if (activityId.startsWith('sow-')) return <IconDocument />
  if (activityId.startsWith('subs-')) return <IconUsers />
  return <IconSparkles />
}

// ─── Activity Row ─────────────────────────────────────────────────────────────

function ActivityRow({ activity, isLast }: { activity: AgentActivity; isLast: boolean }) {
  const statusDot = {
    completed: 'bg-stone-500',
    failed: 'bg-stone-400',
    pending: 'bg-stone-300',
  }[activity.status]

  const statusRing = {
    completed: 'ring-stone-200',
    failed: 'ring-stone-200',
    pending: 'ring-stone-100',
  }[activity.status]

  const statusLabel = {
    completed: 'Completed',
    failed: 'Partial failure',
    pending: 'Pending',
  }[activity.status]

  return (
    <div className="flex gap-3">
      {/* Timeline spine */}
      <div className="flex flex-col items-center flex-shrink-0">
        <div className={`w-6 h-6 rounded-full bg-white ring-2 ${statusRing} flex items-center justify-center text-stone-500 mt-0.5`}>
          {getActivityIcon(activity.id)}
        </div>
        {!isLast && <div className="w-px flex-1 bg-stone-100 mt-1 min-h-[1.5rem]" />}
      </div>

      {/* Content */}
      <div className={`pb-5 min-w-0 flex-1`}>
        <div className="flex items-start justify-between gap-2">
          <div className="min-w-0">
            <p className="text-sm font-medium text-stone-800 leading-snug">{activity.label}</p>
            <p className="text-xs text-stone-500 mt-0.5 leading-relaxed">{activity.description}</p>
            {activity.detail && (
              <p className="text-[11px] text-stone-400 mt-1 font-mono leading-snug">{activity.detail}</p>
            )}
          </div>
          <div className="flex-shrink-0 text-right">
            {activity.timestamp && (
              <p
                className="text-[11px] text-stone-400 whitespace-nowrap"
                title={format(activity.timestamp, 'PPpp')}
              >
                {formatDistanceToNow(activity.timestamp, { addSuffix: true })}
              </p>
            )}
          </div>
        </div>

        {/* Source badges */}
        <div className="flex items-center gap-1.5 mt-2 flex-wrap">
          <span className={`inline-flex items-center gap-1 px-1.5 py-0.5 rounded text-[10px] font-medium ${
            activity.status === 'completed'
              ? 'bg-stone-100 text-stone-600'
              : activity.status === 'failed'
              ? 'bg-stone-100 text-stone-500'
              : 'bg-stone-50 text-stone-400'
          }`}>
            <span className={`w-1.5 h-1.5 rounded-full ${statusDot}`} />
            {statusLabel}
          </span>
          <span className="inline-flex items-center px-1.5 py-0.5 rounded text-[10px] bg-stone-50 text-stone-500 border border-stone-100">
            {activity.model}
          </span>
        </div>
      </div>
    </div>
  )
}

// ─── Stats Bar ────────────────────────────────────────────────────────────────

function StatsBar({ activities }: { activities: AgentActivity[] }) {
  const total = activities.length
  const completed = activities.filter((a) => a.status === 'completed').length
  const aiActions = activities.filter(
    (a) => a.model.includes('GPT') || a.model.includes('OpenAI')
  ).length

  return (
    <div className="grid grid-cols-3 gap-3 mb-6">
      <StatTile label="AI Actions" value={String(aiActions)} />
      <StatTile label="Total Events" value={String(total)} />
      <StatTile label="Completed" value={`${completed}/${total}`} />
    </div>
  )
}

function StatTile({ label, value }: { label: string; value: string }) {
  return (
    <div className="bg-white border border-stone-200 rounded-lg p-3 text-center">
      <p className="text-xs font-bold text-stone-800">{value}</p>
      <p className="text-[10px] uppercase tracking-wider text-stone-400 mt-0.5">{label}</p>
    </div>
  )
}

// ─── Empty State ──────────────────────────────────────────────────────────────

function EmptyState() {
  return (
    <div className="flex flex-col items-center justify-center py-16 text-center">
      <div className="w-10 h-10 rounded-full bg-stone-100 flex items-center justify-center mb-3">
        <IconSparkles />
      </div>
      <p className="text-sm font-medium text-stone-700">No agent activity yet</p>
      <p className="text-xs text-stone-400 mt-1 max-w-xs">
        AI actions will appear here once you generate a SOW, discover subcontractors, or create a bid assessment.
      </p>
    </div>
  )
}

// ─── Panel ────────────────────────────────────────────────────────────────────

export default function AgentActivityPanel({
  opportunity,
  assessment,
}: AgentActivityPanelProps) {
  const activities = useMemo(
    () => deriveActivities(opportunity, assessment),
    [opportunity, assessment]
  )

  return (
    <div className="h-full overflow-y-auto bg-stone-50">
      <div className="max-w-2xl mx-auto px-6 py-6">
        {/* Header */}
        <div className="mb-6">
          <h2 className="text-base font-semibold text-stone-900">Agent Activity</h2>
          <p className="text-xs text-stone-500 mt-0.5">
            Chronological log of AI actions taken on this opportunity
          </p>
        </div>

        {activities.length === 0 ? (
          <EmptyState />
        ) : (
          <>
            <StatsBar activities={activities} />

            {/* Timeline */}
            <div>
              {activities.map((activity, idx) => (
                <ActivityRow
                  key={activity.id}
                  activity={activity}
                  isLast={idx === activities.length - 1}
                />
              ))}
            </div>

            {/* Footer note */}
            <div className="mt-4 pt-4 border-t border-stone-100">
              <p className="text-[10px] text-stone-400 leading-relaxed">
                Activity is derived from existing opportunity data (SOW timestamps, parsed attachment metadata, subcontractor discovery records). No separate activity log table is used.
              </p>
            </div>
          </>
        )}
      </div>
    </div>
  )
}
